[project]
name = "autogen-backend"
version = "0.1.0"
description = "autogen-backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.4.8.2",
    "autogen-ext[azure,openai]>=0.4.8.2",
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "pydantic-settings>=2.8.1",
    "uvicorn[standard]>=0.34.0",
]
[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
